-- USER
-- Password : 123456
INSERT INTO USERMODULE.USER_TABLE (CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, USER_ID, VERSION, EMAIL, FIRST_NAME, LAST_NAME, MOBILE_NUMBER, NATIONAL_ID, PASSWORD, STATUS, USER_NAME)
VALUES (null, SYSDATE, null, SYSDATE, 1, 0, 'admin@gmail.com','ادمین', 'ادمین',
        '09120000000', '0000000000', '-315835415#-1295172027!2', 'ACTIVE', 'admin');

--ROLE
INSERT INTO ROLE_TABLE (ROLE_ID, DESCRIPTION, NAME, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, VERSION)
VALUES (1, 'مدیریت', 'Manager', 1, SYSDATE, 1, SYSDATE, 0);
INSERT INTO ROLE_TABLE (ROLE_ID, DESCRIPTION, NAME, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, VERSION)
VALUES (2, 'ادمین', 'Admin', 1, SYSDATE, 1, SYSDATE, 0);

-- PERMISSION
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (1, 'Manager', 'مدیریت', null, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (2, 'ٍAdmin', 'ادمین', null, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (10, 'User Management', 'مدیریت کاربر', null, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (11, 'Role Management', 'مدیریت نقش', null, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (12, 'Permission Management', 'مدیریت دسترسی', null, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (13, 'Error Management', 'مدیریت خطا', null, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (14, 'General History Management', 'مدیریت تاریخچه عمومی', null, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (15, 'Option Management', 'مدیریت اطلاعات', null, 1, 1, SYSDATE, SYSDATE, 0);

INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (100, 'Add User', 'ایجاد کاربر', 10, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (101, 'Activate User', 'فعالسازی کاربر', 10, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (102, 'User Change Status', 'تغییر وضعیت کاربر', 10, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (103, 'Search Users', 'جستجو کاربران', 10, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (106, 'Search User', 'جستجو کاربر', 10, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (107, 'User Login History', 'سابقه ورود کاربر', 10, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (108, 'Search Users By Permission', 'جستجو کاربران بر اساس دسترسی', 10, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (110, 'Add Role', 'ایجاد نقش', 11, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (111, 'Search Role', 'جستجو نقش', 11, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (112, 'Role List', 'لیست نقش', 11, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (113, 'Update Role', 'ویرایش نقش', 11, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (120, 'Add Permission', 'ایجاد دسترسی', 12, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (121, 'Add Permission To Role', 'افزودن دسترسی به نقش', 12, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (122, 'Search Permission', 'جستجو دسترسی', 12, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (123, 'Permission Parents', 'لیست گروه دسترسی', 12, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (124, 'Permission Tree List', 'لیست درختی دسترسی', 12, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (125, 'Update Permission', 'ویرایش دسترسی', 12, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (130, 'Search Error', 'جستجو خطاها', 13, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (131, 'Search Errors', 'جستجو خطا', 13, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (140, 'Search General History', 'جستجو تاریخچه عمومی', 14, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (150, 'Option List', 'لیست اطلاعات', 15, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (151, 'Update Option', 'ویرایش اطلاعات', 15, 1, 1, SYSDATE, SYSDATE, 0);
INSERT INTO PERMISSION_TABLE (PERMISSION_ID, CODE, DESCRIPTION, PARENT_ID, CREATED_BY, LAST_MODIFIED_BY, CREATED_DATE, LAST_MODIFIED_DATE, VERSION)
VALUES (152, 'Reload Option', 'بارگذاری مجدد اطلاعات', 15, 1, 1, SYSDATE, SYSDATE, 0);

INSERT INTO ROLE_TABLE_PERMISSIONS (ROLE_ENTITY_ROLE_ID, PERMISSIONS_PERMISSION_ID)
VALUES (1, 1);
INSERT INTO ROLE_TABLE_PERMISSIONS (ROLE_ENTITY_ROLE_ID, PERMISSIONS_PERMISSION_ID)
VALUES (1, 101);

INSERT INTO USER_ROLE_PERMISSION_TABLE (USER_ROLE_PERMISSION_ID, ROLE_ROLE_ID, USER_USER_ID)
VALUES (1, 1, 1);
INSERT INTO USER_ROLE_PERMISSION_MAP (USER_ROLE_ID, PERMISSION_ID)
VALUES (1, 1);

INSERT INTO OPTION_TABLE (OPTION_ID, CODE, VALUE, DESCRIPTION, CREATED_DATE, CREATED_BY,  LAST_MODIFIED_BY, LAST_MODIFIED_DATE, VERSION)
VALUES (1, 'TOKEN_EXPIRATION_MIN', '60', 'انقضای توکن', SYSDATE, 1, 1, SYSDATE, 0);
INSERT INTO OPTION_TABLE (OPTION_ID, CODE, VALUE, DESCRIPTION, CREATED_DATE, CREATED_BY,  LAST_MODIFIED_BY, LAST_MODIFIED_DATE, VERSION)
VALUES (2, 'SECRET_KEY', '1877be90db705cee371fc7adc7e54309118cb4590d1082fffad327998b476429c9256cb5e06b271ad63d47e73ac8b123cab43da9db46f2cc00069b5073ef994e', 'کلید امنیتی', SYSDATE, 1, 1, SYSDATE, 0);
INSERT INTO OPTION_TABLE (OPTION_ID, CODE, VALUE, DESCRIPTION, CREATED_DATE, CREATED_BY,  LAST_MODIFIED_BY, LAST_MODIFIED_DATE, VERSION)
VALUES (3, 'OPTION_ACCESS_USERS', 'admin', 'نام کاربری برای دسترسی تنظیمات سیستم', SYSDATE, 1, 1, SYSDATE, 0);
INSERT INTO OPTION_TABLE (OPTION_ID, CODE, VALUE, DESCRIPTION, CREATED_DATE, CREATED_BY,  LAST_MODIFIED_BY, LAST_MODIFIED_DATE, VERSION)
VALUES (4, 'DOCUMENT_FOLDER_PATH', '//192.168.1.1/Archive//UserModule', 'آدرس محل ذخیره فایل ها', SYSDATE, 1, 1, SYSDATE, 0);
INSERT INTO OPTION_TABLE (OPTION_ID, CODE, VALUE, DESCRIPTION, CREATED_DATE, CREATED_BY,  LAST_MODIFIED_BY, LAST_MODIFIED_DATE, VERSION)
VALUES (5, 'DOCUMENT_FOLDER_USERNAME', 'blue', 'نام کاربری جهت ذخیره فایل', SYSDATE, 1, 1, SYSDATE, 0);
INSERT INTO OPTION_TABLE (OPTION_ID, CODE, VALUE, DESCRIPTION, CREATED_DATE, CREATED_BY,  LAST_MODIFIED_BY, LAST_MODIFIED_DATE, VERSION)
VALUES (6, 'DOCUMENT_FOLDER_PASSWORD', '123', 'رمز عبور جهت ذخیره فایل', SYSDATE, 1, 1, SYSDATE, 0);
INSERT INTO OPTION_TABLE (OPTION_ID, CODE, VALUE, DESCRIPTION, CREATED_DATE, CREATED_BY,  LAST_MODIFIED_BY, LAST_MODIFIED_DATE, VERSION)
VALUES (7, 'FORGET_PASSWORD_MESSAGE_TEXT', 'کد جهت تغییر رمز عبور: {code}', 'متن پیامک فراموشی رمز عبور', SYSDATE, 1, 1, SYSDATE, 0);
